name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * 1'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run copybara
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Download copybara.
          curl -SLO https://github.com/oilpan-gc/export-automation/releases/download/copybara/copybara_deploy.jar
          # Use github credentials for pushing.
          gh auth setup-git
          git config --global user.name 'Cheng'
          git config --global user.email 'cheng@zcbenz.com'
          # Run copybara.
          java -jar ./copybara_deploy.jar copy.bara.sky
          # Create PR.
          gh pr create --base main --head update-latest-cppgc --title 'Update to latest V8 changes' --body ''
